# Generated by Django 5.2.2 on 2025-06-10 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='URL original para encurtar', max_length=2048)),
                ('short_code', models.CharField(blank=True, db_index=True, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Deixe vazio para nunca expirar', null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortened_urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'URL Encurtada',
                'verbose_name_plural': 'URLs Encurtadas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['short_code'], name='urls_shorte_short_c_0fd298_idx'), models.Index(fields=['created_at'], name='urls_shorte_created_5a851b_idx')],
            },
        ),
    ]
